### ISSUE TITLE
RoR group project: Kanban board

### ISSUE THREAD

**Issue by umair-rao** [George7h/Recipe-app#21]
We are two group members for this project. We have split tasks according to the requirements. Below is the link of the Project Kanban Board. You're requested to please review the Kanban Board. 

https://github.com/George7h/Recipe-app/projects/1

**Comment by omar-muhamad** [comment]
# Changes Required ♻️
### Hi @umair-rao and @George7h,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Changes Required) Aspects to improve: ♻️

- [ ] There are a lot of Kanban cards that have no description, Please ensure that all cards have a proper description.
Here is an example of these cards:

![image](https://github.com/George7h/Recipe-app/assets/68796232/4fe12850-aa93-444e-ab5a-c5f0d2d1c6cd)
![image](https://github.com/George7h/Recipe-app/assets/68796232/a0a74cf2-e467-4230-990a-6862dc1b0020)

- [ ] There is one card without the number of points [Xpt] that indicates hours of work taken to do this task. Please add it to the card title as you did with the rest of the cards.

![image](https://github.com/George7h/Recipe-app/assets/68796232/78af77b5-e3cf-45f8-abb1-1e8da2984d48)

- [ ] There are no cards about the creation of the `Public recipe list` and `General shopping list view` pages. As per the project requirements, please add them.

![image](https://github.com/George7h/Recipe-app/assets/68796232/8f73128d-fcd9-49d9-80d0-a67b14e702b6)
![image](https://github.com/George7h/Recipe-app/assets/68796232/8ca7d5fb-c545-4402-93db-4bf64ff30ecc) 


## [Optional] suggestions:

- [ ] There are some repeated cards with the same functionality but for different modules. Please append them in one card for example `The N+1 cards` and `The specs cards`.

![image](https://github.com/George7h/Recipe-app/assets/68796232/5fc69338-c23d-4004-b0dc-4a230cef7eed)
![image](https://github.com/George7h/Recipe-app/assets/68796232/2dd0c776-6fa7-4402-9d20-4b754f6742cb)


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by umair-rao** [comment]
All the suggested changes have been implemented. You are requested to please review.

**Comment by souad988** [comment]
Hi @umair-rao , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Fair distribution of work
Description added to all cards

 ## Required Changes ♻️
_Check the comments under the review._
just please remove this card as requested by the previous reviewer
![Screenshot from 2024-01-29 12-48-19](https://github.com/George7h/Recipe-app/assets/59707859/65a1dd42-a77c-457c-a159-dde494778682)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by George7h** [comment]
Thank you @souad988. We have removed the card as requested.

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @George7h, and @umair-rao👋, 

Your project is complete!  There is nothing else to say other than... it's time to close it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
